### ISSUE TITLE
Adding buttons to cell

### ISSUE THREAD

**Issue by itunyk** [provideal/MMGridView#5]
Hi René,
I'm trying to add buttons to cell.
In "MMGridViewDefaultCell" I added UIButton *del, and @property. 
In "MMGridViewDefaultCell." I synthesized it and adde to initWithFrame
//Delete button
        self.deleteIssue = [[UIButton alloc] initWithFrame:CGRectNull];
        self.deleteIssue = [UIButton buttonWithType:UIButtonTypeCustom];
        [self.deleteIssue addTarget:self action:(@selector(deleteIssueAction)) forControlEvents:UIControlStateNormal];
        [self.deleteIssue setImage:[UIImage imageNamed:@"deleteIssue.png"] forState:UIControlStateNormal];
        [self addSubview:self.deleteIssue
In layoutSubviews I added:
    //Delete button
    self.deleteIssue.frame = CGRectMake(-5, -5, 17, 17);
In MMGridViewCell.h I added
- (void)deleteButtonPressed {
  SEL deleteIssueAction = @selector(deleteBut:);
  [gridView performSelector:deleteIssueAction withObject:self];
  NSLog(@"deletePressed");
  }

Button appears in MyViewController, but when I'm taped on it nothing gonna happen.
Can U help me fix that? 

Thank you.

**Comment by provideal** [comment]
Hi,

the cell is not designed to hold "interactive" subviews like buttons or other controls. That was not in my focus. Anyway you should look at MMGridViewCell.touchesBegan and MMGridViewCell.touchesEnded. They probably eat your button event. Instead of changing MMGridViewCell and MMGridViewDefaultCell, have you considered to create a custom subclass?

I'll create a feature request to support "interactive" controls as cell subviews but i can't implement this in the next weeks due to other projects. If you find a working solution please submit a pull request.

Regards,

René
