### ISSUE TITLE
Check/Optimize for iPad. Provide native iPad example.

### ISSUE THREAD

**Issue by provideal** [provideal/MMGridView#8]

**Comment by HeadWorx** [comment]
that will be great, i tested and have a slow performance while switching between pages. thx

**Comment by provideal** [comment]
Have you tested with the latest master code? Francis Chong (siuying) submitted code today that dramatically improved rendering speed.

**Comment by HeadWorx** [comment]
Hi, yes i teste it with todays code. i notice that when i use the simulator with iphone 4.3 works great, but when i use on ipad 4.3 simulator in the begining is ok but if you continue to slide it starts to freeze. 

In real ipad the situation is the same. first is good but then starts to freeze. 

ps: by the way, should swith to "cell page" when double click?

great job guys.

**Comment by provideal** [comment]
Ok, I will have a look as soon as I find time. I'm currently very busy with another (paid) project. Thanks for reporting.

Regards, René

**Comment by provideal** [comment]
@HeadWorx, can u check with the latest code. Should be good now.

Regards, René

**Comment by HeadWorx** [comment]
Hello provideal,

sorry about the delay, but only today i test the new code. That problem is solved, great job!

however, i found two more problems, if you set for example the grid to numberOfCollumns to 1 and rows to 3 you will find:

1 - when you landscape your device, you will get 3 collumns instead of 3 rows
2 - when you back to portrait view (beside page 1), it will not resize as it should.

Great work guys.
Regards,
Head_Worx

**Comment by provideal** [comment]
Hi Head_Worx,

In landscape mode I use a very simple approach and just switch rows and columns. Normally I use something like 2 cols and 3 rows in portrait mode. In landscape MMGridViews change this setting to 3 cols and 2 rows, which looks good. I edge cases when u use 1 col this approach doesn't fit right. Maybe we need independent settings for portrait and landscape. I will have a look at it, when I find time.

Regards, René
